// This file has been generated by the dart_json_mapper v2.2.13
// https://github.com/k-paxian/dart-json-mapper
// @dart = 2.12
import 'NewsBO.dart' as x0 show NewsBO, Articles, Source;
import 'package:dart_json_mapper/dart_json_mapper.dart' show JsonMapper, JsonMapperAdapter, SerializationOptions, DeserializationOptions, typeOf;
// No output from reflectable, there is no `main`.
final newsBoGeneratedAdapter = JsonMapperAdapter(
  title: 'newyorktimes',
  url: 'package:newyorktimes/BO/NewsBO/NewsBO.dart',
  reflectableData: null,
  memberSymbolMap: null,
  valueDecorators: {
    typeOf<List<x0.NewsBO>>(): (value) => value.cast<x0.NewsBO>(),
    typeOf<Set<x0.NewsBO>>(): (value) => value.cast<x0.NewsBO>(),
    typeOf<List<x0.Articles>>(): (value) => value.cast<x0.Articles>(),
    typeOf<Set<x0.Articles>>(): (value) => value.cast<x0.Articles>(),
    typeOf<List<x0.Source>>(): (value) => value.cast<x0.Source>(),
    typeOf<Set<x0.Source>>(): (value) => value.cast<x0.Source>()
},
  enumValues: {

});

Future<JsonMapper> initializeJsonMapperAsync({Iterable<JsonMapperAdapter> adapters = const [], SerializationOptions? serializationOptions, DeserializationOptions? deserializationOptions}) => Future(() => initializeJsonMapper(adapters: adapters, serializationOptions: serializationOptions, deserializationOptions: deserializationOptions));

JsonMapper initializeJsonMapper({Iterable<JsonMapperAdapter> adapters = const [], SerializationOptions? serializationOptions, DeserializationOptions? deserializationOptions}) {
  JsonMapper.globalSerializationOptions = serializationOptions ?? JsonMapper.globalSerializationOptions;
  JsonMapper.globalDeserializationOptions = deserializationOptions ?? JsonMapper.globalDeserializationOptions;    
  JsonMapper.enumerateAdapters([...adapters, newsBoGeneratedAdapter], (JsonMapperAdapter adapter) {
    
    JsonMapper().useAdapter(adapter);
  });
  return JsonMapper();
}