// This file has been generated by the dart_json_mapper v2.2.13
// https://github.com/k-paxian/dart-json-mapper
// @dart = 2.12
import 'ArchiveBO.dart' as x0 show ArchiveBO, Responses, Docs, Multimedias, Legacy, Headline, Keywords, Byline, Person, Meta;
import 'package:dart_json_mapper/dart_json_mapper.dart' show JsonMapper, JsonMapperAdapter, SerializationOptions, DeserializationOptions, typeOf;
// No output from reflectable, there is no `main`.
final archiveBoGeneratedAdapter = JsonMapperAdapter(
  title: 'newyorktimes',
  url: 'package:newyorktimes/BO/ArchiveBO/ArchiveBO.dart',
  reflectableData: null,
  memberSymbolMap: null,
  valueDecorators: {
    typeOf<List<x0.ArchiveBO>>(): (value) => value.cast<x0.ArchiveBO>(),
    typeOf<Set<x0.ArchiveBO>>(): (value) => value.cast<x0.ArchiveBO>(),
    typeOf<List<x0.Responses>>(): (value) => value.cast<x0.Responses>(),
    typeOf<Set<x0.Responses>>(): (value) => value.cast<x0.Responses>(),
    typeOf<List<x0.Docs>>(): (value) => value.cast<x0.Docs>(),
    typeOf<Set<x0.Docs>>(): (value) => value.cast<x0.Docs>(),
    typeOf<List<x0.Multimedias>>(): (value) => value.cast<x0.Multimedias>(),
    typeOf<Set<x0.Multimedias>>(): (value) => value.cast<x0.Multimedias>(),
    typeOf<List<x0.Legacy>>(): (value) => value.cast<x0.Legacy>(),
    typeOf<Set<x0.Legacy>>(): (value) => value.cast<x0.Legacy>(),
    typeOf<List<x0.Headline>>(): (value) => value.cast<x0.Headline>(),
    typeOf<Set<x0.Headline>>(): (value) => value.cast<x0.Headline>(),
    typeOf<List<x0.Keywords>>(): (value) => value.cast<x0.Keywords>(),
    typeOf<Set<x0.Keywords>>(): (value) => value.cast<x0.Keywords>(),
    typeOf<List<x0.Byline>>(): (value) => value.cast<x0.Byline>(),
    typeOf<Set<x0.Byline>>(): (value) => value.cast<x0.Byline>(),
    typeOf<List<x0.Person>>(): (value) => value.cast<x0.Person>(),
    typeOf<Set<x0.Person>>(): (value) => value.cast<x0.Person>(),
    typeOf<List<x0.Meta>>(): (value) => value.cast<x0.Meta>(),
    typeOf<Set<x0.Meta>>(): (value) => value.cast<x0.Meta>()
},
  enumValues: {

});

Future<JsonMapper> initializeJsonMapperAsync({Iterable<JsonMapperAdapter> adapters = const [], SerializationOptions? serializationOptions, DeserializationOptions? deserializationOptions}) => Future(() => initializeJsonMapper(adapters: adapters, serializationOptions: serializationOptions, deserializationOptions: deserializationOptions));

JsonMapper initializeJsonMapper({Iterable<JsonMapperAdapter> adapters = const [], SerializationOptions? serializationOptions, DeserializationOptions? deserializationOptions}) {
  JsonMapper.globalSerializationOptions = serializationOptions ?? JsonMapper.globalSerializationOptions;
  JsonMapper.globalDeserializationOptions = deserializationOptions ?? JsonMapper.globalDeserializationOptions;    
  JsonMapper.enumerateAdapters([...adapters, archiveBoGeneratedAdapter], (JsonMapperAdapter adapter) {
    
    JsonMapper().useAdapter(adapter);
  });
  return JsonMapper();
}